name: CMake Build Matrix

on:
  push:
    branches:
      - master
      - develop

jobs:
  get-dependencies:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: catchorg/Catch2
        ref:  master
    - uses: actions/checkout@v2
      with:
        repository: chriskohlhoff/asio
        ref:  master

  build-unixes:
    needs: get-dependencies

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run:  mkdir build && cd build && cmake ..
    - name: build
      run:  cmake --build build
    - name: test
      run:  cd build && ctest

  build-windows:
    needs: get-dependencies

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest -C "Debug"

