# Note differences between Unix variants and Windows shell when invoking
# multiple commands on one line - bash uses double ampersand, powershell
# uses semi-colon
#
# Currently there is duplication, specially for the dependency management,
# this should be refactored in the future
name: CMake Build Matrix

on:
  push:
    branches:
      - master
      - develop

jobs:

  build-unixes:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: main
    - name: checkout-catch
      uses: actions/checkout@v2
      with:
        repository: catchorg/Catch2
        ref:  master
        path: Catch2
    - name: checkout-asio
      uses: actions/checkout@v2
      with:
        repository: chriskohlhoff/asio
        ref:  master
        path: asio
    - name: configure-cmake
      run:  mkdir build && cd build && cmake ../main
    - name: build
      run:  cd build && cmake --build .
    - name: unit-test
      run:  cd build && ctest

  build-windows:

    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: main
    - name: checkout-catch
      uses: actions/checkout@v2
      with:
        repository: catchorg/Catch2
        ref:  master
        path: Catch2
    - name: checkout-asio
      uses: actions/checkout@v2
      with:
        repository: chriskohlhoff/asio
        ref:  master
        path: asio
    - name: configure-cmake
      run: mkdir build; cd build; cmake ../main
    - name: build
      run: cd build; cmake --build .
    - name: unit-test
      run: cd build; ctest -C "Debug"

  generate-docs:

    runs-on: ubuntu-latest
    needs: [ build-unixes, build-windows ]

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: get-dependent-apps
      run: sudo apt-get install doxygen && sudo apt-get install graphviz
    - name: configure-cmake
      run:  mkdir build && cd build && cmake -DUTILITY_RACK_OPT_BUILD_DOCS:bool=ON ..
    - name: build-docs
      run:  cd build && cmake --build . --target docs
    - name: publish-to-git
      uses: peaceiris/actions-gh-pages@v3
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html
        force_orphan: true
