# 
name: Generate Docs

on:
  push:
    branches:
      - master

jobs:

  generate-docs:

    runs-on: ubuntu-latest

    steps:
    - name: get-dependent-apps
      run: sudo apt-get install doxygen && sudo apt-get install graphviz
    - name: checkout-master
      uses: actions/checkout@v2
      with:
        path: master_branch
    - name: configure-cmake
      run:  mkdir build_docs && cd build_docs && cmake -DUTILITY_RACK_OPT_BUILD_DOCS:bool=ON ../master_branch
    - name: build-docs
      run:  cd build_docs && cmake --build . --target docs
    - name: remove-build-dir
      run:  rm -rf build_docs
    - name: checkout-gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: pages_branch
    - name: sync-git-add-commit-push
      run: |
            rsync -a --quiet --delete master_branch pages_branch
            cd pages_branch
            git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git config --local user.name  "${GITHUB_ACTOR}"
            git add .
            git commit -a -m "Commit for generated doc files"
            git push
